Module3 task1
htmlacademy-adaptive/122095-cat-energy-25 pull request #4
Opened 2022-04-23 04:56 UTC by neo217

styled all pages

2022-04-27 04:34 UTC, costigans requested changes

2022-04-27 04:34 UTC, costigans commented on source/catalog.html
> +      </button>
А для чего убрал из под `nav`?

2022-04-27 04:34 UTC, costigans commented on source/catalog.html
> +                  <dd class="product__total">500 г</dd>
По мне это ненужное усложнение. Ты вполне можешь использовать для стилизации `.product__options dt` и `.product__options dd`

2022-04-27 04:34 UTC, costigans commented on source/form.html
> +                <input class="cat-data__input" type="text" name="cat-name" placeholder="барсик" required>
Не нужна привязка к содержимому, БЭМ-классы лучше именовать по смыслу которые они несут, здесь это всего лишь инпуты, лейблы, просто текст (или заголовок) и филдсеты.
Попробуй так их и назвать, сможешь переиспользовать на других группах элементов (вроде `program-selected` и т.д.). То что где-то есть отличия — работа для модификаторов

2022-04-27 04:34 UTC, costigans commented on source/less/blocks/additionally.less
> +}
Так вот совершенно не надо, я вот не понимаю что содержится в `checkbox-input`.
Используй универсальные блоки, и таких проблем не будет.

2022-04-27 04:34 UTC, costigans commented on source/less/blocks/gift.less
> +}
На самом деле это же не блок `gift`, это просто блок с информацией и фоновым изображениям. То что на макете информация про подарок для БЭМ-блоков не имеет значения.

2022-04-27 04:34 UTC, costigans commented on source/less/blocks/additional-products.less
> +  font-family: "Arial", sans-serif;
Выноси правила шрифтов в переменные

2022-04-27 04:34 UTC, costigans commented on source/less/blocks/additional-products.less
> +  color: #222222;
Цвета тоже переносим в переменные

2022-04-27 04:34 UTC, costigans commented on source/less/blocks/mixins.less
> +}
Вот примерно с такими именами и должны быть твои элементы для формы, и эти миксины буду не нужны.
И не будет лишних блоков и файлов под них.

2022-04-27 18:37 UTC, neo217 commented on source/catalog.html
> +      </button>
Для того чтобы легче управлять расположением кнопки

2022-05-01 01:06 UTC, merged

2022-05-01 01:12 UTC, costigans commented on source/less/blocks/variables.less
> +@icon_grey: #d3d3d3;
Для понимания, что это цвет, лучше в имена переменных добавить слово `color`.
Например, переменная `@status_error`, сейчас ты помнишь что в ней содержится, а спустя время? Или когда проект разрастётся? А другой разработчик поймёт, что это цвет?